---
title: "tables_ba"
author: "Sara Østergaard"
date: "16/12/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
### Packages ###
library(pacman)
p_load(
  tidyverse, devtools, kableExtra
)
#devtools::install_github("haozhu233/kableExtra")

### Data ###
saved <- read_csv("Results_csv/saved_results_real.csv") %>% 
  mutate(
    "b_sex_cond_dist" = abs(b_sex_cond_med-(boot::inv.logit(true_sex_cond)-boot::inv.logit(true_base))),
    "cot" = str_extract(analysis_type, "[a-z]+_[a-z]+"),
    "cot" = ifelse(cot == "pp_linear", 0, 1), #cot: 0 = linear, 1 = citation
    "cot" = as.factor(cot),
    "pb" = ifelse(is.na(pub_method), 0, 1),
    "pb" = as.factor(pb)
  )
meta <- read_csv("Results_csv/meta_results_real.csv") %>% 
  mutate(
    "abs_dist_pp_l" = abs(meta_sex_cond_estimate_pp_l-(boot::inv.logit(meta_true_sex_cond)-boot::inv.logit(meta_true_base))),
    "abs_dist_pp_l_pb_sym" = abs(meta_sex_cond_estimate_pp_l_pb_sym-(boot::inv.logit(meta_true_sex_cond)-boot::inv.logit(meta_true_base))),
    "abs_dist_pp_l_pb_asym" = abs(meta_sex_cond_estimate_pp_l_pb_asym-(boot::inv.logit(meta_true_sex_cond)-boot::inv.logit(meta_true_base))),
    "abs_dist_pp_c" = abs(meta_sex_cond_estimate_pp_c-(boot::inv.logit(meta_true_sex_cond)-boot::inv.logit(meta_true_base))),
    "abs_dist_pp_c_pb_sym" = abs(meta_sex_cond_estimate_pp_c_pb_sym-(boot::inv.logit(meta_true_sex_cond)-boot::inv.logit(meta_true_base))),
    "abs_dist_pp_c_pb_asym" = abs(meta_sex_cond_estimate_pp_c_pb_asym-(boot::inv.logit(meta_true_sex_cond)-boot::inv.logit(meta_true_base)))
  )
```
### Table 1: meaned results for last experiment by cot and pb (0,1)
```{r}
# creating table
mean_saved_cot <- saved %>%  filter(expt == max(expt))%>% 
  group_by(true_sex_cond,cot,pb) %>% 
  mutate(
    cot = ifelse(cot == 0, "linear","citation")
          ) %>% 
  summarize(
    mean_estimate = round(mean(b_sex_cond_med),3),
    sd_estimate = round(sd(b_sex_cond_med),3),
    mean_uncertainty = round(mean(b_sex_cond_upper - b_sex_cond_lower),3),
    sd_uncertainty = round(sd(b_sex_cond_upper - b_sex_cond_lower),3),
    mean_dist = round(mean(b_sex_cond_dist),3),
    sd_dist = round(sd(b_sex_cond_dist),3)
  ) %>% select(true_sex_cond, cot, pb, mean_dist, sd_dist, mean_uncertainty, sd_uncertainty)

mean_saved_cot <- mean_saved_cot %>% 
  mutate(
    mean_dist = paste(mean_dist, " (",sd_dist,")", sep = "" ),
    mean_uncertainty = paste(mean_uncertainty, " (",sd_uncertainty,")", sep = "" )
  ) %>% select(true_sex_cond, cot, pb, mean_dist, mean_uncertainty)

# latex code
kbl(mean_saved_cot, booktabs = T, format = "latex") %>%
  kable_styling(latex_options = "striped")

```

###Table 2: difference in estimates for the two types of pb
```{r}
# creating table
saved_last_pp <- saved %>%  group_by(true_sex_cond,repeat_id,analysis_type) %>% 
  mutate(n_exp = sum(pub_true))%>% 
  filter(expt == max(expt)) %>% 
  summarise(
    estimate = b_sex_cond_med,
    CI_lower = b_sex_cond_lower,
    CI_upper = b_sex_cond_upper, 
    analysis_type,
    n_exp
    )

saved_last_pp <- saved_last_pp %>% 
  mutate(
    dist = estimate - (boot::inv.logit(true_sex_cond) - 0.5),
    dist_lower = CI_lower - (boot::inv.logit(true_sex_cond) - 0.5),
    dist_upper = CI_upper - (boot::inv.logit(true_sex_cond) - 0.5)
  )

pb_type <- saved_last_pp %>%
  group_by(analysis_type) %>%
  summarize(
    mean_uncertainty = round(mean(CI_upper - CI_lower),3),
    sd_uncertainty = round(sd(CI_upper - CI_lower),3),
    mean_dist = round(mean(abs(dist)),3),
    sd_dist = round(sd(abs(dist)),3),
    mean_exp = round(mean(n_exp),2)
  ) %>% 
  mutate(
    "cot" = ifelse(grepl("citation",analysis_type), "citation","linear"),
    "pb" = ifelse(grepl("asym",analysis_type), "asym","sym"),
    "pb" = ifelse(!grepl("sym",analysis_type), NA,pb),
    "mean_dist" = paste(mean_dist, " (",sd_dist,")", sep = "" ),
    "mean_uncertainty" = paste(mean_uncertainty, " (",sd_uncertainty,")", sep = "" )
  ) %>% 
  filter(!is.na(pb)) %>% select(cot,pb,mean_dist,mean_uncertainty)

# latex code
kbl(pb_type, booktabs = T, format = "latex") %>%
  kable_styling(latex_options = c("striped"))
```


###Appendix: published studies 
```{r}
meta_melt <- melt(meta, id.vars = c("meta_true_sex_cond", "meta_true_base", "meta_true_sex", "meta_true_cond")) %>% 
  filter(variable == "pub_pp_l"|variable == "pub_pp_l_pb_sym"|variable == "pub_pp_l_pb_asym"|
           variable == "pub_pp_c"|variable == "pub_pp_c_pb_sym"|variable == "pub_pp_c_pb_asym") %>% 
  rename("analysis_type"="variable", "pub"="value") %>% 
  mutate("analysis_type" = sub("pub_","",analysis_type),
         "pb_method" = ifelse(grepl("asym",analysis_type), "asym","sym"),
         "pb_method" = ifelse(grepl("sym",analysis_type), pb_method,NA),
         "pub"=as.numeric(pub))

pub_meta <- meta_melt %>% 
  group_by(pb_method,meta_true_sex_cond, analysis_type) %>% 
  summarise(
    "mean_published" = round(mean(pub),3),
    "sd" = round(sd(pub),3)
  ) %>% 
  rename("cot"="analysis_type") %>% 
  mutate(
    "cot" = ifelse(grepl("c",cot), "citation","linear"),
    "mean_published" = paste(mean_published, " (",sd,")", sep = "" )
  ) %>% filter(!(is.na(pb_method))) %>% select(-sd)

# latex code
kbl(pub_meta, booktabs = T, format = "latex") %>%
  kable_styling(latex_options = c("striped"))
```

